### ISSUE TITLE
This scraper is invalid due to change in naming pagination

### ISSUE THREAD

**Issue by 0mars** [javierlopeza/goodreads-scraper#6]
It throws:
```
Traceback (most recent call last):
  File "books_scraper.py", line 272, in <module>
    scraper.run()
  File "books_scraper.py", line 258, in run
    self.check_cookie()
  File "books_scraper.py", line 254, in check_cookie
    raise Exception('Must use a valid session cookie!')
Exception: Must use a valid session cookie!
```

**Comment by 0mars** [comment]
for non-logged in users, there is absolutely no pagination what so ever

**Comment by lacie-life** [comment]
I met the same problem. Have you fixed that? @0mars
